### ISSUE TITLE
wordclockfunctions.ino_english not showing twelve (hour)

### ISSUE THREAD

**Issue by crimsonclyde** [techniccontroller/wordclock_esp8266#24]
There is a problem in [this](https://github.com/techniccontroller/wordclock_esp8266/commit/2dfdca36fac5ccffc9b1f42c08bf9ce554bb8770) version [wordclockfunctions.ino_english](https://github.com/techniccontroller/wordclock_esp8266/blob/main/wordclockfunctions.ino_english)

Twelve is not correctly displayed. All other minutes and hours work properly. Only 12 doesn't work.

Log output "multicastUDP_receiver.py"
```bash
('192.168.x.y', 8123) :  Wordclock 2.0: time as String: IT IS QUARTER PAST
('192.168.x.y', 8123) :  Wordclock 2.0: Heartbeat, state: Clock, FreeHeap: 36400, HeapFrag: 1, MaxFreeBlock: 36152
('192.168.x,y', 8123) :  Wordclock 2.0: time as String: IT IS QUARTER PAST
...
('192.168.x.y', 8123) :  Wordclock 2.0: time as String: IT IS HALF PAST
('192.168.x.y', 8123) :  Wordclock 2.0: Heartbeat, state: Clock, FreeHeap: 36176, HeapFrag: 1, MaxFreeBlock: 35928
('192.168.x.y', 8123) :  Wordclock 2.0: time as String: IT IS HALF PAST
```

According to microcontroller.net the log needs to show the time correctly otherwise the LED matrix is not able to handle the time accordingly. If I find some time I will try to take a closer look into this.

...just a info

**Comment by techniccontroller** [comment]
Hi,

thank you for highlighting this problem. I fixed the issue.

BR
Edgar

**Comment by crimsonclyde** [comment]
Thx for your quick support.
Sorry I wanted to send a merge request :) but you have been much faster to fix the problem.
