### ISSUE TITLE
question about the mentioned button

### ISSUE THREAD

**Issue by RalphGit62** [techniccontroller/wordclock_esp8266#25]
in line 64 of the wordclock_esp8266.ino file you mentioned a button, which has to be connected to port 14. Unfortunatly I don't find any circuitdiagram and now I'm wondering which potential the button should be switched to.

Sorry for the stupid question and thanks a lot for a patient answer.

**Comment by techniccontroller** [comment]
Hello Ralph,

you can find the circuit diagram in the original post on my website: https://techniccontroller.com/word-clock-with-wifi-and-neopixel/ 
(also linked in README)

The push-button is attached to the GND and D5 pin of the ESP8266 NodeMCU Board. I use the internal pullup resistor to pull the input pin to 3.3V (HIGH). When the button is pressed the input sees 0V (LOW).

I hope this clarifies your question.

Best regards
Edgar
