### ISSUE TITLE
A fatal esptool.py error occurred: Write timeout

### ISSUE THREAD

**Issue by SkylightXD** [techniccontroller/wordclock_esp8266#26]
Hallo zusammen,

habt ihr eine Idee, warum das hier schief läuft?

. Variables and constants in RAM (global, static), used 39196 / 80192 bytes (48%)
║   SEGMENT  BYTES    DESCRIPTION
╠══ DATA     1580     initialized variables
╠══ RODATA   6000     constants       
╚══ BSS      31616    zeroed variables
. Instruction RAM (IRAM_ATTR, ICACHE_RAM_ATTR), used 61111 / 65536 bytes (93%)
║   SEGMENT  BYTES    DESCRIPTION
╠══ ICACHE   32768    reserved space for flash instruction cache
╚══ IRAM     28343    code in IRAM    
. Code in flash (default, ICACHE_FLASH_ATTR), used 410900 / 1048576 bytes (39%)
║   SEGMENT  BYTES    DESCRIPTION
╚══ IROM     410900   code in flash   
esptool.py v3.0
Serial port /dev/ttyACM0
Connecting...
A fatal esptool.py error occurred: Write timeout

**Comment by techniccontroller** [comment]
Hi,

funktioniert der Upload eines Beispielscodes (z.B. Blink.ino)? 
Ich würde das erstmal testen, um zu prüfen es am Programmcode oder der Konfiguration liegt.
Ich denke eher zweiteres. 

Bist du sicher, dass der ESP am serial port /dev/ttyACM0 angeschlossen ist? Vielleicht ist das ein anderes Gerät.
Am besten einmal den ESP ausstecken und prüfen ob dann der serial port verschwindet.

Vielleicht auch nochmal die Board-Konfiguration überprüfen (Arduino-IDE -> Werkzeuge):

![image](https://github.com/techniccontroller/wordclock_esp8266/assets/36072504/dce664ed-803a-459f-807d-c29b308270eb)

Viele Grüße
Edgar

**Comment by SkylightXD** [comment]
Danke dir für den Hinweis! Ich glaube es lag am Port ...

**Comment by SkylightXD** [comment]
Danke dir für den Hinweis! Ich glaube es lag am Port ...
